<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atem" nsURI="http://www.ages.net/workbench/templates/dsl/Atem"
    nsPrefix="atem">
  <eClassifiers xsi:type="ecore:EClass" name="AtemModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Template_Status" eType="#//TemplateStatus"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Template_Driver" eType="#//Driver"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Template_head" eType="#//Head"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Template_preface" eType="#//Preface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Template_components"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Head">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Head_components" upperBound="-1"
        eType="#//HeadComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeadComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Driver_RegEx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Driver_Status" eType="#//TemplateStatuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateTitle" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_TemplateTitle_Elements"
        upperBound="-1" eType="#//HeaderFooterFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageKeepWithNext" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_PageKeepWithNext_value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageHeaderEven" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_PageHeader_columns"
        upperBound="-1" eType="#//HeaderFooterColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageHeaderOdd" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_PageHeader_columns"
        upperBound="-1" eType="#//HeaderFooterColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageFooterEven" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_PageHeader_columns"
        upperBound="-1" eType="#//HeaderFooterColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageFooterOdd" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_PageHeader_columns"
        upperBound="-1" eType="#//HeaderFooterColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_HeaderFooterColumn_fragments"
        upperBound="-1" eType="#//HeaderFooterFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterColumnLeft" eSuperTypes="#//HeaderFooterColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterColumnCenter" eSuperTypes="#//HeaderFooterColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterColumnRight" eSuperTypes="#//HeaderFooterColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterText" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterDate" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterDate_Language"
        eType="#//Language"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterPageNumber" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterPageNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterLookup" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_HeaderFooterLookup_Elements"
        upperBound="-1" eType="#//ElementType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterLookup_Language"
        eType="#//Language"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterTitle" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterTitle"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderFooterCommemoration" eSuperTypes="#//HeaderFooterFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_HeaderFooterCommemoration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commemoration" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Commemoration_Elements"
        upperBound="-1" eType="#//HeaderFooterFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_TemplateStatus" eType="#//TemplateStatuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionSwitch" eSuperTypes="#//AbstractComponent #//InfoElementType #//PrefaceElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_VersionSwitch_flag"
        eType="#//VersionSwitchType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VersionSwitchType">
    <eLiterals name="L1" literal="L1"/>
    <eLiterals name="L2" value="1" literal="L2"/>
    <eLiterals name="Both" value="2" literal="Both"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="L1" literal="L1"/>
    <eLiterals name="L2" value="1" literal="L2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceText" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_ResourceTextRef" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_ResourceText_Media_Off"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lookup" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_ResourceTextRef" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Lookup_Media_Off" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Lookup_Override_Mode_Set"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Lookup_OverrideMode"
        eType="#//ModeTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Lookup_Override__Day_Set"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Lookup_OverrideDay"
        eType="#//DowTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDP" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_LDP" upperBound="-1"
        eType="#//LdpType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaggedText" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_TaggedText_tag" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_TaggedText" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Info" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Info_Elements" upperBound="-1"
        eType="#//InfoElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//HeadComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Date_month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Date_day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Date_year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Preface_Elements" upperBound="-1"
        eType="#//PrefaceElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefaceElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//AbstractComponent #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Section_Role" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Section_Elements" upperBound="-1"
        eType="#//SectionElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LdpType"/>
  <eClassifiers xsi:type="ecore:EClass" name="All" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_LiturgicalDayProperties"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenDate" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenYear" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCD" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_MCD_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOW" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NOP" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DOM" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DOP" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DOWN" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DOWT" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOW" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_Eothinon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAEC" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_SundayAfterElevationCross"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SOL" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_StartLukan"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DOL" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_DayLukan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WOLC" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_DayLukan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WDOLC" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_DayLukan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SBT" eSuperTypes="#//LdpType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Display_SundaysBeforeTriodion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateFragment" eSuperTypes="#//AbstractComponent #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//AtemModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefaceFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Preface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionFragment" eSuperTypes="#//AbstractComponent #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Break" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_break_type" eType="#//BreakType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BreakType">
    <eLiterals name="line" literal="line"/>
    <eLiterals name="page" value="1" literal="page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageNumber" eSuperTypes="#//HeadComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_PageNumber_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassThroughHtml" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Passthrough_html_text"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassThroughPdf" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Passthrough_pdf_text"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="#//AbstractComponent #//InfoElementType #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Title_Role" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubTitle" eSuperTypes="#//AbstractComponent #//InfoElementType #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_SubTitle_Role" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//AbstractComponent #//InfoElementType #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Para_Role" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//AbstractComponent #//InfoElementType #//PrefaceElementType #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Block_Role" eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hymn" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Verse" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rubric" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dialog" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reading" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heading1" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heading2" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heading3" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_Elements" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aid" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LitBook" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetLocale" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_SetLocale_V1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_SetLocale_V2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestoreLocale" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_RestoreLocale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemplateStatuses">
    <eLiterals name="NA" literal="NA"/>
    <eLiterals name="Draft" value="1" literal="Draft"/>
    <eLiterals name="Review" value="2" literal="Review"/>
    <eLiterals name="Final" value="3" literal="Final"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Null">
    <eLiterals name="null" literal="null"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModeTypes">
    <eLiterals name="M1" literal="M1"/>
    <eLiterals name="M2" value="1" literal="M2"/>
    <eLiterals name="M3" value="2" literal="M3"/>
    <eLiterals name="M4" value="3" literal="M4"/>
    <eLiterals name="M5" value="4" literal="M5"/>
    <eLiterals name="M6" value="5" literal="M6"/>
    <eLiterals name="M7" value="6" literal="M7"/>
    <eLiterals name="M8" value="7" literal="M8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DowTypes">
    <eLiterals name="D1" literal="D1"/>
    <eLiterals name="D2" value="1" literal="D2"/>
    <eLiterals name="D3" value="2" literal="D3"/>
    <eLiterals name="D4" value="3" literal="D4"/>
    <eLiterals name="D5" value="4" literal="D5"/>
    <eLiterals name="D6" value="5" literal="D6"/>
    <eLiterals name="D7" value="6" literal="D7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BookTypes">
    <eLiterals name="Octochechos" literal="Octochechos"/>
    <eLiterals name="Menaion" value="1" literal="Menaion"/>
    <eLiterals name="Euchologion" value="2" literal="Euchologion"/>
    <eLiterals name="Pentecostarion" value="3" literal="Pentecostarion"/>
    <eLiterals name="Triodion" value="4" literal="Triodion"/>
    <eLiterals name="Horologion" value="5" literal="Horologion"/>
    <eLiterals name="Eothina" value="6" literal="Eothina"/>
    <eLiterals name="Heirmologion" value="7" literal="Heirmologion"/>
    <eLiterals name="Katavasias" value="8" literal="Katavasias"/>
    <eLiterals name="Psalter" value="9" literal="Psalter"/>
    <eLiterals name="Lectionary" value="10" literal="Lectionary"/>
    <eLiterals name="Other" value="11" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Seasons">
    <eLiterals name="Triodion" literal="Triodion"/>
    <eLiterals name="Pentecostarion" value="1" literal="Pentecostarion"/>
    <eLiterals name="Nativity_Fast" value="2" literal="Nativity_Fast"/>
    <eLiterals name="Apostles_Fast" value="3" literal="Apostles_Fast"/>
    <eLiterals name="Dormition_Fast" value="4" literal="Dormition_Fast"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DayOfMonthTypes">
    <eLiterals name="D01" literal="D01"/>
    <eLiterals name="D02" value="1" literal="D02"/>
    <eLiterals name="D03" value="2" literal="D03"/>
    <eLiterals name="D04" value="3" literal="D04"/>
    <eLiterals name="D05" value="4" literal="D05"/>
    <eLiterals name="D06" value="5" literal="D06"/>
    <eLiterals name="D07" value="6" literal="D07"/>
    <eLiterals name="D08" value="7" literal="D08"/>
    <eLiterals name="D09" value="8" literal="D09"/>
    <eLiterals name="D10" value="9" literal="D10"/>
    <eLiterals name="D11" value="10" literal="D11"/>
    <eLiterals name="D12" value="11" literal="D12"/>
    <eLiterals name="D13" value="12" literal="D13"/>
    <eLiterals name="D14" value="13" literal="D14"/>
    <eLiterals name="D15" value="14" literal="D15"/>
    <eLiterals name="D16" value="15" literal="D16"/>
    <eLiterals name="D17" value="16" literal="D17"/>
    <eLiterals name="D18" value="17" literal="D18"/>
    <eLiterals name="D19" value="18" literal="D19"/>
    <eLiterals name="D20" value="19" literal="D20"/>
    <eLiterals name="D21" value="20" literal="D21"/>
    <eLiterals name="D22" value="21" literal="D22"/>
    <eLiterals name="D23" value="22" literal="D23"/>
    <eLiterals name="D24" value="23" literal="D24"/>
    <eLiterals name="D25" value="24" literal="D25"/>
    <eLiterals name="D26" value="25" literal="D26"/>
    <eLiterals name="D27" value="26" literal="D27"/>
    <eLiterals name="D28" value="27" literal="D28"/>
    <eLiterals name="D29" value="28" literal="D29"/>
    <eLiterals name="D30" value="29" literal="D30"/>
    <eLiterals name="D31" value="30" literal="D31"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenDate" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDate_Cases" upperBound="-1"
        eType="#//WhenDateCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDate_Other" eType="#//WhenOther"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenDateCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_WhenDate_Case_Month"
        eType="#//MonthName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDateCase_Days"
        eType="#//AbstractDateCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDateCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDateCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateRange" eSuperTypes="#//AbstractDateCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_DateRange_from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_DateRange_To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateSet" eSuperTypes="#//AbstractDateCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dslDateSet_Values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenDayName" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDayName_Cases"
        upperBound="-1" eType="#//WhenDayNameCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDayName_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenDayNameCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDayNameCase_Days"
        eType="#//AbstractDayNameCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenDayNameCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDayNameCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DayNameRange" eSuperTypes="#//AbstractDayNameCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_DayNameRange_from"
        eType="#//DayOfWeek"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_DayNameRange_To" eType="#//DayOfWeek"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DayNameSet" eSuperTypes="#//AbstractDayNameCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dslDayNameSet_Values" unique="false"
        upperBound="-1" eType="#//DayOfWeek"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PeriodType">
    <eLiterals name="pascha" literal="pascha"/>
    <eLiterals name="pentecostarion" value="1" literal="pentecostarion"/>
    <eLiterals name="triodion" value="2" literal="triodion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenPentecostarionDay" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPentecostarionDay_Cases"
        upperBound="-1" eType="#//WhenPeriodCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPentecostarionDay_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenTriodionDay" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenTriodionDay_Cases"
        upperBound="-1" eType="#//WhenPeriodCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenTriodionDay_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenMovableCycleDay" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenMovableCycleDay_Cases"
        upperBound="-1" eType="#//WhenPeriodCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenMovableCycleDay_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenSundayAfterElevationOfCrossDay"
      eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenSundayAfterElevationOfCrossDay_Cases"
        upperBound="-1" eType="#//WhenDateCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenSundayAfterElevationOfCrossDay_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenLukanCycleDay" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenLukanCycleDay_Cases"
        upperBound="-1" eType="#//WhenPeriodCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenLukanCycleDay_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenPascha" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPascha_true_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPascha_Other_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenOther">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenCase_Other_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenPeriodCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPeriodCase_Days"
        eType="#//AbstractDayCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenPeriodCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDayCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DayRange" eSuperTypes="#//AbstractDayCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_DayRange_from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_Range_To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaySet" eSuperTypes="#//AbstractDayCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dslSetValue_Days" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenModeOfWeek" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenModeOfWeek_Cases"
        upperBound="-1" eType="#//WhenModeOfWeekCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenModeOfWeek_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenModeOfWeekCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenModeOfWeekCase_Days"
        eType="#//ModeOfWeekSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenModeOfWeekCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModeOfWeekSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_ModeOfWeekSet_MOWs"
        unique="false" upperBound="-1" eType="#//ModeTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenSundaysBeforeTriodion" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenSundaysBeforeTriodion_Cases"
        upperBound="-1" eType="#//SundaysBeforeTriodionCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_SundaysBeforeTriodion_Other"
        eType="#//WhenOther" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SundaysBeforeTriodionCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsl_SundaysBeforeTriodionCase_Days"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_SundaysBeforeTriodionCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeek">
    <eLiterals name="Sunday" literal="Sunday"/>
    <eLiterals name="Monday" value="1" literal="Monday"/>
    <eLiterals name="Tuesday" value="2" literal="Tuesday"/>
    <eLiterals name="Wednesday" value="3" literal="Wednesday"/>
    <eLiterals name="Thursday" value="4" literal="Thursday"/>
    <eLiterals name="Friday" value="5" literal="Friday"/>
    <eLiterals name="Saturday" value="6" literal="Saturday"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MonthName">
    <eLiterals name="Jan" literal="Jan"/>
    <eLiterals name="Feb" value="1" literal="Feb"/>
    <eLiterals name="Mar" value="2" literal="Mar"/>
    <eLiterals name="Apr" value="3" literal="Apr"/>
    <eLiterals name="May" value="4" literal="May"/>
    <eLiterals name="Jun" value="5" literal="Jun"/>
    <eLiterals name="Jul" value="6" literal="Jul"/>
    <eLiterals name="Aug" value="7" literal="Aug"/>
    <eLiterals name="Sep" value="8" literal="Sep"/>
    <eLiterals name="Oct" value="9" literal="Oct"/>
    <eLiterals name="Nov" value="10" literal="Nov"/>
    <eLiterals name="Dec" value="11" literal="Dec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenExists" eSuperTypes="#//AbstractComponent #//SectionElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenExists_Cases" upperBound="-1"
        eType="#//WhenExistsCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenExists_Other" eType="#//WhenOther"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenExistsCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenExistsCase_Ref"
        eType="ecore:EClass ../../../../../../../net.ages.workbench.resources.dsl/src-gen/net/ages/workbench/resources/dsl/Ares.ecore#//Definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsl_WhenExistsCase_True_actions"
        upperBound="-1" eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
